// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNR9zErRyfnDczBNUOuE895z8fepH0QNQ',
    appId: '1:608554177460:web:a84da31beaff3f07a118e1',
    messagingSenderId: '608554177460',
    projectId: 'a2zecom',
    authDomain: 'a2zecom.firebaseapp.com',
    storageBucket: 'a2zecom.firebasestorage.app',
    measurementId: 'G-8VG12QE0H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Sm_dy6R635eEF3L6BZUjDmXjYIX4_Lo',
    appId: '1:608554177460:android:e12e1ff6ab44a5b4a118e1',
    messagingSenderId: '608554177460',
    projectId: 'a2zecom',
    storageBucket: 'a2zecom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMJDKiBOpCRYSVEXoc-FwiduUnGnHAGmk',
    appId: '1:608554177460:ios:bcaa20cf2877d9eca118e1',
    messagingSenderId: '608554177460',
    projectId: 'a2zecom',
    storageBucket: 'a2zecom.firebasestorage.app',
    iosBundleId: 'com.example.a2zecom',
  );
}
